// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LoanFundManagement.Migrations
{
    [DbContext(typeof(LoanFundDbContext))]
    [Migration("20241216054735_UpdateGuarantorLoansNullable")]
    partial class UpdateGuarantorLoansNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("LoanFundManagement.Models.Person", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("BirthCertificateNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("BirthPlace")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FatherName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsGuarantor")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("TEXT");

                    b.Property<string>("NationalCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tel")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.HasKey("PersonId");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("LoanFundManagement.Models.Tvam", b =>
                {
                    b.Property<int>("KeyVam")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CHkserial")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("NumberVam")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Paytype")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RowPerson")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("VamAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("VamDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("VamNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Zamenid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Zamenname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("KeyVam");

                    b.HasIndex("RowPerson");

                    b.HasIndex("Zamenid");

                    b.ToTable("Tvams");
                });

            modelBuilder.Entity("LoanFundManagement.Models.Tvam", b =>
                {
                    b.HasOne("LoanFundManagement.Models.Person", "Person")
                        .WithMany()
                        .HasForeignKey("RowPerson")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LoanFundManagement.Models.Person", "Zamen")
                        .WithMany("GuarantorLoans")
                        .HasForeignKey("Zamenid")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Person");

                    b.Navigation("Zamen");
                });

            modelBuilder.Entity("LoanFundManagement.Models.Person", b =>
                {
                    b.Navigation("GuarantorLoans");
                });
#pragma warning restore 612, 618
        }
    }
}
